from .scene_gen_node import NODE_CLASS_MAPPINGS as MUSIC_VIDEO_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MUSIC_VIDEO_DISPLAY
from .scene_gen_movies_node import NODE_CLASS_MAPPINGS as MOVIES_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MOVIES_DISPLAY

# Merge mappings from both modules
NODE_CLASS_MAPPINGS = {**MUSIC_VIDEO_MAPPINGS, **MOVIES_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**MUSIC_VIDEO_DISPLAY, **MOVIES_DISPLAY}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
